# Generated by Django 3.2.11 on 2022-03-16 19:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bodystream',
            field=wagtail.core.fields.StreamField([('rtfblock', wagtail.core.blocks.RichTextBlock()), ('imgblock', wagtail.images.blocks.ImageChooserBlock()), ('videoblock', wagtail.embeds.blocks.EmbedBlock())], blank=True, verbose_name='Вміст статті'),
        ),
    ]
