# Generated by Django 3.2.11 on 2022-03-16 20:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220316_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bodystream',
            field=wagtail.core.fields.StreamField([('rtfblock', wagtail.core.blocks.RichTextBlock(label='Текст', template='home/blocks/textblock.html')), ('imgblock', wagtail.images.blocks.ImageChooserBlock(label='Зображення', template='home/blocks/imgblock.html')), ('videoblock', wagtail.embeds.blocks.EmbedBlock(label='Відео'))], blank=True, verbose_name='Вміст статті'),
        ),
    ]
