# Generated by Django 3.2.11 on 2022-03-24 20:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220324_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermodel',
            name='bodytext',
            field=wagtail.core.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
