# Generated by Django 3.2.11 on 2022-02-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['date']},
        ),
    ]
